version: "3.8"
services:
  mongoDb:
    image: mongo:latest
    container_name: mongoDb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: suryansh
      MONGO_INITDB_ROOT_PASSWORD: development1234
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: